// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_qn_quadrature_cpp
double compute_qn_quadrature_cpp(List kde_list, NumericMatrix quad_grid, NumericVector quad_weights, int n_vars);
RcppExport SEXP _dagMI_compute_qn_quadrature_cpp(SEXP kde_listSEXP, SEXP quad_gridSEXP, SEXP quad_weightsSEXP, SEXP n_varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type kde_list(kde_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type quad_grid(quad_gridSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type quad_weights(quad_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_qn_quadrature_cpp(kde_list, quad_grid, quad_weights, n_vars));
    return rcpp_result_gen;
END_RCPP
}
// compute_qn_montecarlo_cpp
List compute_qn_montecarlo_cpp(List kde_list, NumericMatrix samples, int n_vars, int n_samples);
RcppExport SEXP _dagMI_compute_qn_montecarlo_cpp(SEXP kde_listSEXP, SEXP samplesSEXP, SEXP n_varsSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type kde_list(kde_listSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type samples(samplesSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_qn_montecarlo_cpp(kde_list, samples, n_vars, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// compute_test_stat_cpp
double compute_test_stat_cpp(NumericMatrix data, List kde_list, NumericVector h_values, double qn, int n_vars);
RcppExport SEXP _dagMI_compute_test_stat_cpp(SEXP dataSEXP, SEXP kde_listSEXP, SEXP h_valuesSEXP, SEXP qnSEXP, SEXP n_varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type kde_list(kde_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h_values(h_valuesSEXP);
    Rcpp::traits::input_parameter< double >::type qn(qnSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_test_stat_cpp(data, kde_list, h_values, qn, n_vars));
    return rcpp_result_gen;
END_RCPP
}
// compute_density_correction_cpp
NumericVector compute_density_correction_cpp(NumericMatrix data, List kde_list, int n_vars);
RcppExport SEXP _dagMI_compute_density_correction_cpp(SEXP dataSEXP, SEXP kde_listSEXP, SEXP n_varsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type data(dataSEXP);
    Rcpp::traits::input_parameter< List >::type kde_list(kde_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_density_correction_cpp(data, kde_list, n_vars));
    return rcpp_result_gen;
END_RCPP
}
// compute_moments_cpp
NumericVector compute_moments_cpp(NumericMatrix h_values, int n_vars, int n_obs);
RcppExport SEXP _dagMI_compute_moments_cpp(SEXP h_valuesSEXP, SEXP n_varsSEXP, SEXP n_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type h_values(h_valuesSEXP);
    Rcpp::traits::input_parameter< int >::type n_vars(n_varsSEXP);
    Rcpp::traits::input_parameter< int >::type n_obs(n_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_moments_cpp(h_values, n_vars, n_obs));
    return rcpp_result_gen;
END_RCPP
}
// gauss_legendre_cpp
List gauss_legendre_cpp(int n);
RcppExport SEXP _dagMI_gauss_legendre_cpp(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(gauss_legendre_cpp(n));
    return rcpp_result_gen;
END_RCPP
}
// transform_quadrature_cpp
List transform_quadrature_cpp(NumericVector nodes, NumericVector weights, double a, double b);
RcppExport SEXP _dagMI_transform_quadrature_cpp(SEXP nodesSEXP, SEXP weightsSEXP, SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nodes(nodesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(transform_quadrature_cpp(nodes, weights, a, b));
    return rcpp_result_gen;
END_RCPP
}
// kde_eval_cpp
NumericVector kde_eval_cpp(NumericVector x_eval, NumericVector x_data, double bandwidth);
RcppExport SEXP _dagMI_kde_eval_cpp(SEXP x_evalSEXP, SEXP x_dataSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_eval_cpp(x_eval, x_data, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kde_bivariate_eval_cpp
NumericMatrix kde_bivariate_eval_cpp(NumericMatrix xy_eval, NumericMatrix xy_data, NumericVector bandwidth);
RcppExport SEXP _dagMI_kde_bivariate_eval_cpp(SEXP xy_evalSEXP, SEXP xy_dataSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type xy_eval(xy_evalSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type xy_data(xy_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_bivariate_eval_cpp(xy_eval, xy_data, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kde_loo_cpp
NumericVector kde_loo_cpp(NumericVector x_data, double bandwidth);
RcppExport SEXP _dagMI_kde_loo_cpp(SEXP x_dataSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_loo_cpp(x_data, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kde_cv_score_cpp
double kde_cv_score_cpp(NumericVector x_data, double bandwidth);
RcppExport SEXP _dagMI_kde_cv_score_cpp(SEXP x_dataSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_cv_score_cpp(x_data, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kde_eval_truncated_cpp
NumericVector kde_eval_truncated_cpp(NumericVector x_eval, NumericVector x_data, double bandwidth, double min_density);
RcppExport SEXP _dagMI_kde_eval_truncated_cpp(SEXP x_evalSEXP, SEXP x_dataSEXP, SEXP bandwidthSEXP, SEXP min_densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    Rcpp::traits::input_parameter< double >::type min_density(min_densitySEXP);
    rcpp_result_gen = Rcpp::wrap(kde_eval_truncated_cpp(x_eval, x_data, bandwidth, min_density));
    return rcpp_result_gen;
END_RCPP
}
// kde_conditional_cpp
NumericVector kde_conditional_cpp(NumericVector y_eval, NumericVector x_condition, NumericVector y_data, NumericVector x_data, double bandwidth_x, double bandwidth_y, double min_density);
RcppExport SEXP _dagMI_kde_conditional_cpp(SEXP y_evalSEXP, SEXP x_conditionSEXP, SEXP y_dataSEXP, SEXP x_dataSEXP, SEXP bandwidth_xSEXP, SEXP bandwidth_ySEXP, SEXP min_densitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_eval(y_evalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_condition(x_conditionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y_data(y_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth_x(bandwidth_xSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth_y(bandwidth_ySEXP);
    Rcpp::traits::input_parameter< double >::type min_density(min_densitySEXP);
    rcpp_result_gen = Rcpp::wrap(kde_conditional_cpp(y_eval, x_condition, y_data, x_data, bandwidth_x, bandwidth_y, min_density));
    return rcpp_result_gen;
END_RCPP
}
// density_correction_factor_cpp
NumericVector density_correction_factor_cpp(NumericMatrix x_data, List kde_objects, double power);
RcppExport SEXP _dagMI_density_correction_factor_cpp(SEXP x_dataSEXP, SEXP kde_objectsSEXP, SEXP powerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< List >::type kde_objects(kde_objectsSEXP);
    Rcpp::traits::input_parameter< double >::type power(powerSEXP);
    rcpp_result_gen = Rcpp::wrap(density_correction_factor_cpp(x_data, kde_objects, power));
    return rcpp_result_gen;
END_RCPP
}
// kde_multivariate_cpp
NumericVector kde_multivariate_cpp(NumericMatrix x_eval, NumericMatrix x_data, NumericVector bandwidth);
RcppExport SEXP _dagMI_kde_multivariate_cpp(SEXP x_evalSEXP, SEXP x_dataSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_multivariate_cpp(x_eval, x_data, bandwidth));
    return rcpp_result_gen;
END_RCPP
}
// kde_weighted_cpp
NumericVector kde_weighted_cpp(NumericVector x_eval, NumericVector x_data, NumericVector weights, double bandwidth);
RcppExport SEXP _dagMI_kde_weighted_cpp(SEXP x_evalSEXP, SEXP x_dataSEXP, SEXP weightsSEXP, SEXP bandwidthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_eval(x_evalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_data(x_dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type bandwidth(bandwidthSEXP);
    rcpp_result_gen = Rcpp::wrap(kde_weighted_cpp(x_eval, x_data, weights, bandwidth));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dagMI_compute_qn_quadrature_cpp", (DL_FUNC) &_dagMI_compute_qn_quadrature_cpp, 4},
    {"_dagMI_compute_qn_montecarlo_cpp", (DL_FUNC) &_dagMI_compute_qn_montecarlo_cpp, 4},
    {"_dagMI_compute_test_stat_cpp", (DL_FUNC) &_dagMI_compute_test_stat_cpp, 5},
    {"_dagMI_compute_density_correction_cpp", (DL_FUNC) &_dagMI_compute_density_correction_cpp, 3},
    {"_dagMI_compute_moments_cpp", (DL_FUNC) &_dagMI_compute_moments_cpp, 3},
    {"_dagMI_gauss_legendre_cpp", (DL_FUNC) &_dagMI_gauss_legendre_cpp, 1},
    {"_dagMI_transform_quadrature_cpp", (DL_FUNC) &_dagMI_transform_quadrature_cpp, 4},
    {"_dagMI_kde_eval_cpp", (DL_FUNC) &_dagMI_kde_eval_cpp, 3},
    {"_dagMI_kde_bivariate_eval_cpp", (DL_FUNC) &_dagMI_kde_bivariate_eval_cpp, 3},
    {"_dagMI_kde_loo_cpp", (DL_FUNC) &_dagMI_kde_loo_cpp, 2},
    {"_dagMI_kde_cv_score_cpp", (DL_FUNC) &_dagMI_kde_cv_score_cpp, 2},
    {"_dagMI_kde_eval_truncated_cpp", (DL_FUNC) &_dagMI_kde_eval_truncated_cpp, 4},
    {"_dagMI_kde_conditional_cpp", (DL_FUNC) &_dagMI_kde_conditional_cpp, 7},
    {"_dagMI_density_correction_factor_cpp", (DL_FUNC) &_dagMI_density_correction_factor_cpp, 3},
    {"_dagMI_kde_multivariate_cpp", (DL_FUNC) &_dagMI_kde_multivariate_cpp, 3},
    {"_dagMI_kde_weighted_cpp", (DL_FUNC) &_dagMI_kde_weighted_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_dagMI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
