# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_qn_quadrature_cpp <- function(kde_list, quad_grid, quad_weights, n_vars) {
    .Call(`_dagMI_compute_qn_quadrature_cpp`, kde_list, quad_grid, quad_weights, n_vars)
}

compute_qn_montecarlo_cpp <- function(kde_list, samples, n_vars, n_samples) {
    .Call(`_dagMI_compute_qn_montecarlo_cpp`, kde_list, samples, n_vars, n_samples)
}

compute_test_stat_cpp <- function(data, kde_list, h_values, qn, n_vars) {
    .Call(`_dagMI_compute_test_stat_cpp`, data, kde_list, h_values, qn, n_vars)
}

compute_density_correction_cpp <- function(data, kde_list, n_vars) {
    .Call(`_dagMI_compute_density_correction_cpp`, data, kde_list, n_vars)
}

compute_moments_cpp <- function(h_values, n_vars, n_obs) {
    .Call(`_dagMI_compute_moments_cpp`, h_values, n_vars, n_obs)
}

gauss_legendre_cpp <- function(n) {
    .Call(`_dagMI_gauss_legendre_cpp`, n)
}

transform_quadrature_cpp <- function(nodes, weights, a, b) {
    .Call(`_dagMI_transform_quadrature_cpp`, nodes, weights, a, b)
}

kde_eval_cpp <- function(x_eval, x_data, bandwidth) {
    .Call(`_dagMI_kde_eval_cpp`, x_eval, x_data, bandwidth)
}

kde_bivariate_eval_cpp <- function(xy_eval, xy_data, bandwidth) {
    .Call(`_dagMI_kde_bivariate_eval_cpp`, xy_eval, xy_data, bandwidth)
}

kde_loo_cpp <- function(x_data, bandwidth) {
    .Call(`_dagMI_kde_loo_cpp`, x_data, bandwidth)
}

kde_cv_score_cpp <- function(x_data, bandwidth) {
    .Call(`_dagMI_kde_cv_score_cpp`, x_data, bandwidth)
}

kde_eval_truncated_cpp <- function(x_eval, x_data, bandwidth, min_density = 1e-10) {
    .Call(`_dagMI_kde_eval_truncated_cpp`, x_eval, x_data, bandwidth, min_density)
}

kde_conditional_cpp <- function(y_eval, x_condition, y_data, x_data, bandwidth_x, bandwidth_y, min_density = 1e-10) {
    .Call(`_dagMI_kde_conditional_cpp`, y_eval, x_condition, y_data, x_data, bandwidth_x, bandwidth_y, min_density)
}

density_correction_factor_cpp <- function(x_data, kde_objects, power) {
    .Call(`_dagMI_density_correction_factor_cpp`, x_data, kde_objects, power)
}

kde_multivariate_cpp <- function(x_eval, x_data, bandwidth) {
    .Call(`_dagMI_kde_multivariate_cpp`, x_eval, x_data, bandwidth)
}

kde_weighted_cpp <- function(x_eval, x_data, weights, bandwidth) {
    .Call(`_dagMI_kde_weighted_cpp`, x_eval, x_data, weights, bandwidth)
}

